FROM node:20-alpine

ARG DATABASE_URL

WORKDIR /app

COPY package.json package-lock.json turbo.json ./

COPY apps/frontend ./apps/frontend

COPY packages/database ./packages/database

RUN npm install -g pnpm@10.5.2

RUN pnpm install

RUN pnpm run generate:db

RUN cd apps/frontend && pnpm run build

EXPOSE 3002

ENV DATABASE_URL=${DATABASE_URL}

CMD [ "pnpm", "run", "start:frontend" ]

